AWSTemplateFormatVersion: "2010-09-09"
Description: "Stack to deploy spring hello world"
Parameters:
  ElasticBeanstalkApp:
    Description: The name of the Elastic Beanstalk Application to deploy
    Type: String
  ElasticBeanstalkAppVersion:
    Description: A version of the Elastic Beanstalk App to deploy
    Type: String
  ElasticBeanstalkEnvName:
    Description: EB Environment to deploy to
    Type: String
Resources:
  ElasticBeanstalkEnvironment:
    Type: "AWS::ElasticBeanstalk::Environment"
    Properties:
      EnvironmentName: !Ref ElasticBeanstalkEnvName
      ApplicationName: !Ref ElasticBeanstalkApp
      VersionLabel: !Ref ElasticBeanstalkAppVersion
      TemplateName:
        Ref: ElasticBeanstalkConfigurationTemplate
      PlatformArn: !Sub "arn:aws:elasticbeanstalk:${AWS::Region}::platform/Corretto 8 running on 64bit Amazon Linux 2/3.2.15"

  ElasticBeanstalkConfigurationTemplate:
    Type: "AWS::ElasticBeanstalk::ConfigurationTemplate"
    Properties:
      ApplicationName: !Ref ElasticBeanstalkApp
      SolutionStackName: "64bit Amazon Linux 2 v3.2.15 running Corretto 8"
      OptionSettings:
        - Namespace: "aws:elasticbeanstalk:environment"
          OptionName: "EnvironmentType"
          Value: "LoadBalanced"
        - ResourceName: "AWSEBEC2LaunchTemplate"
          Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: "IamInstanceProfile"
          Value: "aws-elasticbeanstalk-ec2-role"
        - ResourceName: "AWSEBAutoScalingGroup"
          Namespace: "aws:autoscaling:asg"
          OptionName: "MaxSize"
          Value: "4"
        - ResourceName: "AWSEBAutoScalingGroup"
          Namespace: "aws:autoscaling:asg"
          OptionName: "MinSize"
          Value: "1"
        - Namespace: "aws:autoscaling:launchconfiguration"
          OptionName: "InstanceType"
          Value: "t2.micro"
        - Namespace: "aws:cloudformation:template:parameter"
          OptionName: "EnvironmentVariables"
          Value: "M2=/usr/local/apache-maven/bin,M2_HOME=/usr/local/apache-maven,GRADLE_HOME=/usr/local/gradle"
        - Namespace: "aws:cloudformation:template:parameter"
          OptionName: "InstancePort"
          Value: "80"
        - Namespace: "aws:cloudformation:template:parameter"
          OptionName: "InstanceTypeFamily"
          Value: "t2"
        - Namespace: "aws:ec2:instances"
          OptionName: "InstanceTypes"
          Value: "t2.micro, t2.small"
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: "M2"
          Value: "/usr/local/apache-maven/bin"
        - Namespace: "aws:elasticbeanstalk:application:environment"
          OptionName: "M2_HOME"
          Value: "/usr/local/apache-maven"
        - Namespace: "aws:elasticbeanstalk:command"
          OptionName: "DeploymentPolicy"
          Value: "AllAtOnce"
        - ResourceName: "AWSEBV2LoadBalancerTargetGroup"
          Namespace: "aws:elasticbeanstalk:environment:process:default"
          OptionName: "HealthCheckPath"
          Value: "/"
        - ResourceName: "AWSEBV2LoadBalancerTargetGroup"
          Namespace: "aws:elasticbeanstalk:environment:process:default"
          OptionName: "Port"
          Value: "80"
